services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: jonatan
      WORDPRESS_DB_PASSWORD: haslo
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp_data:/var/www/html
    depends_on:
      - db
    networks:
      - wp_network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: jonatan
      MYSQL_PASSWORD: haslo
      MYSQL_ROOT_PASSWORD: haslo1
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - wp_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress
      - phpmyadmin
    networks:
      - wp_network

#  apache:
#    image: httpd:latest
#    restart: always
#    volumes:
#      - ./wp_data:/usr/local/apache2/htdocs/
#    ports:
#      - "8081:80"
#    networks:
#      - wp_network

#  apache:
#    image: php:8.2-apache
#    restart: always
#    ports:
#      - "8081:80"
#    volumes:
#      - ./wp_data:/var/www/html
#    networks:
#      - wp_network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8082:80"  # Access phpMyAdmin via port 8082
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: haslo1
    depends_on:
      - db
    networks:
      - wp_network

volumes:
  db_data:
  wp_data:

networks:
  wp_network:
    driver: bridge
 
